NMS: 1
SEED: 10            # random seed

DEBUG: 1            # turns on debugging mode
VERBOSE: 0          # turns on verbose mode in the output console

# TRAIN_FLIST: C:\\Users\\Administrator\\Desktop\\misf-main\\misf-main\\data\\face.txt
# VAL_FLIST: C:\\Users\\Administrator\\Desktop\\misf-main\\misf-main\\data\\face.txt
# TEST_FLIST: C:\\Users\\Administrator\\Desktop\\misf-main\\misf-main\\data\\face.txt

# TRAIN_MASK_FLIST: C:\\Users\\Administrator\\Desktop\\misf-main\\misf-main\\data\\mask.txt
# VAL_MASK_FLIST: C:\\Users\\Administrator\\Desktop\\misf-main\\misf-main\\data\\mask.txt
# TEST_MASK_FLIST: C:\\Users\\Administrator\\Desktop\\misf-main\\misf-main\\data\\mask.txt

TRAIN_FLIST: E:\\face.txt
VAL_FLIST: E:\\face.txt
TEST_FLIST: E:\\face.txt

TRAIN_MASK_FLIST: E:\\mask.txt
VAL_MASK_FLIST: E:\\face.txt
TEST_MASK_FLIST: E:\\face.txt
LR: 0.0001                    # learning rate
D2G_LR: 0.1                   # discriminator/generator learning rate ratio
BETA1: 0.0                    # adam optimizer beta1
BETA2: 0.9                    # adam optimizer beta2

INPUT_SIZE: 256               # input image size for training 0 for original size
MAX_ITERS: 3.5e5                # maximum number of iterations to train the model

L1_LOSS_WEIGHT: 1             # l1 loss weight
FM_LOSS_WEIGHT: 10            # feature-matching loss weight
STYLE_LOSS_WEIGHT: 250        # style loss weight
CONTENT_LOSS_WEIGHT: 0.1      # perceptual loss weight
INPAINT_ADV_LOSS_WEIGHT: 0.1  # adversarial loss weight

GAN_LOSS: nsgan               # nsgan | lsgan | hinge
GAN_POOL_SIZE: 0              # fake images pool size


SAMPLE_INTERVAL: 10         # how many iterations to wait before sampling (0: never)
SAMPLE_SIZE: 5               # number of images to sample
LOG_INTERVAL: 100000              # how many iterations to wait before logging training status (0: never)


MASK_REVERSE: 0                 # 1 reverse dunhuang, 0 no
MASK_THRESHOLD: 0               # 100 dunhuang


GPU: [0]            # list of gpu ids
BATCH_SIZE: 1                 # input batch size for training

SAVE_INTERVAL: 1000        # how many iterations to wait before saving model (0: never)
EVAL_INTERVAL: 200000000             # how many iterations to wait before model evaluation (0: never)

TRAIN_SAMPLE_INTERVAL: 1000
EVAL_SAMPLE_INTERVAL: 200


TRAIN_SAMPLE_SAVE: E:\\result\\train_sample
EVAL_SAMPLE_SAVE: E:\\result\\eval_sample
TEST_SAMPLE_SAVE: E:\\result\\test_20


MODEL_LOAD: celebA_InpaintingModel
